name = "AlgebraicRL"
uuid = "c16e2c52-81b3-496d-9adf-f7ef61ccdb53"
authors = ["Georgios Bakirtzis", "Tyler Ingebrand"]
version = "0.1.2"

[deps]
AlgebraicDynamics = "5fd6ff03-a254-427e-8840-ba658f502e32"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"

[compat]
AlgebraicDynamics = "0.1"
GR = "0.64, 0.66, 0.71"
ReinforcementLearning = "0.10"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
